# Generated by Django 5.0.4 on 2024-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="user",
            new_name="cart",
        ),
    ]
